---
# Role tasks

- name: Configure issue and issue.net
  become: true
  block:

    - name: Login message /etc/issue
      template:
        src: issue.j2
        dest: /etc/issue
        backup: yes

    - name: Login message /etc/issue.net
      template:
        src: issue.net.j2
        dest: /etc/issue.net
        backup: yes

    - name: Check /etc/issue.net in /etc/ssh/sshd_config
      vars:
          contents: "{{ lookup('file', '/etc/ssh/sshd_config') }}"
      assert:
        that:
          - "'Banner /etc/issue.net' in contents"
