---
# Role tasks

- name: Configure issue and issue.net
  block:
    - name: Configure login message in /etc/issue
      ansible.builtin.template:
        src: issue.j2
        dest: /etc/issue
        mode: 0644

    - name: Configure login message in /etc/issue.net
      ansible.builtin.template:
        src: issue.net.j2
        dest: /etc/issue.net
        mode: 0644
  tags:
    - role::issue
